# Generated by Django 3.0.2 on 2020-02-10 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0006_auto_20200208_0812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=250)),
                ('card_number', models.CharField(max_length=16)),
                ('exp_date', models.DateTimeField()),
                ('cvc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('province', models.CharField(max_length=250, null=True)),
                ('zip_code', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_username', models.CharField(max_length=250, null=True)),
                ('facebook_username', models.CharField(max_length=250, null=True)),
                ('linkedin_username', models.CharField(max_length=250, null=True)),
                ('discord_username', models.CharField(max_length=250, null=True)),
                ('github_username', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('card', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Card')),
                ('interests', models.ManyToManyField(blank=True, to='articles.Tag')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Location')),
                ('social', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Social')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
