# Generated by Django 3.0.2 on 2020-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200210_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default='NP', max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
