# Generated by Django 3.0.2 on 2020-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200210_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
