# Generated by Django 3.0.2 on 2020-01-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=320)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('upvotes', models.IntegerField(blank=True, default=0)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('content', models.TextField()),
                ('is_drafted', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('SC', 'SCIENCE'), ('TG', 'TECHNOLOGY'), ('FD', 'FOOD'), ('AR', 'ART'), ('LT', 'LITERATURE'), ('RN', 'RANDOM'), ('PH', 'PHILOSOPHY'), ('MM', 'MUSIC&MOVIES'), ('TS', 'TVSERIES'), ('GM', 'GAMES')], default='RN', max_length=2)),
                ('tags', models.ManyToManyField(blank=True, to='articles.Tag')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
