# Generated by Django 3.0.2 on 2020-01-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200117_1542'),
        ('articles', '0002_auto_20200112_0814'),
    ]

    operations = [
    ]
