# Generated by Django 3.0.2 on 2020-01-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_merge_20200123_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated_at']},
        ),
    ]
