# Generated by Django 3.0.2 on 2020-01-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200113_0912'),
        ('articles', '0004_auto_20200123_1046'),
    ]

    operations = [
    ]
