# Generated by Django 3.0.2 on 2020-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200127_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('AR', 'ART'), ('FD', 'FOOD'), ('GM', 'GAMES'), ('RN', 'RANDOM'), ('SC', 'SCIENCE'), ('TS', 'TVSERIES'), ('TG', 'TECHNOLOGY'), ('LT', 'LITERATURE'), ('PH', 'PHILOSOPHY'), ('MM', 'MUSIC&MOVIES')], default='RN', max_length=2),
        ),
    ]
