# Generated by Django 3.0.2 on 2020-02-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200208_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published_at']},
        ),
    ]
